version: '2.1'

services:
  docs:
    image: ghcr.io/wombatcyberlabs/lab-content-example-docs:main
    restart: always
    hostname: docs
    ports:
      - "80:80"
    networks:
      lab_net:
        ipv4_address: 10.13.37.10
  uptimechecker:
    image: ghcr.io/wombatcyberlabs/lab-utility-uptimechecker:main
    restart: always
    hostname: uptimechecker
    ports:
      - "8080:8080"
    volumes:
      - ./serviceconfig.json:/app/config.json:ro
    networks:
      lab_net:
        ipv4_address: 10.13.37.11

  mortalwombat:
    image: ghcr.io/wombatcyberlabs/lab-content-example-mortalwombat:main
    restart: always
    hostname: mortalwombat
    ports:
      - "8083:8000"
    networks:
      lab_net:
        ipv4_address: 10.13.37.12

networks:
  lab_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.13.37.0/24
